:sparkles: feat: add ingress spec
cloud-club/cloudclub-operator pull request #17
Opened 2024-06-09 14:10 UTC by synoti21

2024-06-13 03:10 UTC, tae2089 requested changes

2024-06-13 03:10 UTC, tae2089 commented on internal/driver/application.go
> +					Host: "example.com",
이거 example.com으로 고정하지 말고 appSpec에 변수 선언해주시면 좋을거 같아요~

2024-06-16 10:27 UTC, synoti21 commented on internal/driver/application.go
> +					Host: "example.com",
AppSpec에 선언했습니다!

2024-06-16 12:17 UTC, tae2089 approved these changes

2024-06-16 12:17 UTC, merged